apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      server: web
  template:
    metadata:
      name: affinity-pod
      labels:
        server: web
    spec:
      affinity:
        nodeAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution: 
#            - weight: 70
#              preference:
#                matchExpressions:
#                  - key: zone
#                    operator: In
#                    values: 
#                      - east
#                      - west
#            - weight: 100
#              preference:
#                matchExpressions:
#                  - key: envnnnn
#                    operator: In
#                    values:
#                    - prodabbb
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                    - prodabc
      containers:
        - name: aff-con
          image:  busybox
          args:
          - sleep
          - "9999"
---
apiVersion: v1
kind: Service
metadata: 
  name: mysvc
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    server: web




 





