apiVersion: apps/v1
kind: Deployment
metadata:
   name: deploy
spec:
  replicas: 6
  selector:
    matchLabels:
      role: prefer
  template:
     matadata:
       name: affinity-pod
       labels:
         role: prefer
     spec:
       affinity:
         podAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
             - weight: 100
               podAffinityTerm:
                 labelSelector:
                   matchExpressions:
                     - key: env
                       operator: In
                       values: 
                         - prod
                 topologyKey: kubernetes.io/hostname 
        containers:
          - name: httpd
            image: httpd
            ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
  selector:
    role: prefer


