apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: affinity
spec:
  replicas: 6
  selector:
    matchLabels:
      role: prefer
  template:
    metadata:
      name: affinity-pod
      labels:
        role: prefer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - prod
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    role: prefer

