apiVersion: v1
kind: Pod
metadata:
  name: all-pod
  labels:
    app: prod
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: mycon
      image: httpd
      ports:
        - containerPort: 80
          #          name: index.html
      env:
        - name: apache
          value: /appl
        - name: apr
          value: /appl/apr
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
      livenessProbe:
              #        httpGet:
              #          path: /index.html
              #          port: 80
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 3
      readinessProbe:
              #        httpGet:
              #          path: /index.html
              #          port: 80
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 3
  initContainers:
    - name: busy
      image: busybox:1.28
      command: ['sh', '-c', 'sleep 5']




