apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-env
data:
  dbname: mysql
  dbpwd: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      role: cm-example
  template:
    metadata:
      name: cm-pod
      labels:
        role: cm-example
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cm-env
              
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc-cm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    role: cm-example
 





