apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
data:
  index.html: |
    <H1> Hello ConfigMap </H1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      role: cm-example
  template:
    metadata:
      name: cm-pod
      labels:
        role: cm-example
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: cm-vol
              mountPath: /usr/share/nginx/html/
              readOnly: true
      volumes:
        - name: cm-vol
          configMap:
            name: cm
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc-cm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    role: cm-example
 





