apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeploy
  labels:
    comp: app1
spec:
  replicas: 3
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      comp: app
  template:
    metadata:
      name: deploy-pod
      labels:
        comp: app
    spec:
      containers:
        - name: deploy-tomcat
          image: leaddevops/kubeserve:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
  labels:
    comp: mysvc-labels
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 31500
  selector:
    comp: app






