apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeploy1
  labels:
    comp: app2
spec:
  replicas: 3
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      comp: app1
  template:
    metadata:
      name: deploy-pod
      labels:
        comp: app1
    spec:
      containers:
        - name: deploy-tomcat
          image: leaddevops/kubeserve:v2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc1
  labels:
    comp: mysvc-labels
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 80
      nodePort: 32500
  selector:
    comp: app1






