apiVersion: v1
kind: Pod
metadata:
  name: limits-pod
  labels:
    env: pod
    app: tomcat
spec:
  containers:
    - name: tomcat-con
      image: tomcat
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 600m
          memory: 150Mi
        limits:
          cpu: 700m
          memory: 200Mi

