apiVersion: apps/v1
kind: Deployment
metadata: 
  name: label-deploy
  labels:
    server: deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      name: label-pod
      labels:
        env: prod
    spec:
      nodeSelector:
        env: prod
      containers:
        - name: label-con
          image: httpd
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    env: prod

