apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    role: pv
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/pvData


  
