apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: httpd
      image: httpd
      volumeMounts:
        - mountPath: /test
          name: pvc-vol
  volumes:
    - name: pvc-vol
      persistentVolumeClaim:
        claimName: pvc

