apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    role: pvc
spec:
  storageClassName: standard
  volumeName: pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

