apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 3
  selector:
    app: tomcat
  template:
    metadata:
      name: pod1
      labels:
        app: tomcat
    spec:
      containers:
        - name: mycon
          image: lerndevops/tomcat:8.5.47
          ports:
            - containerPort: 8080
  
