apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  username: cGFzc2FiYwo=
  password: cGFzc2FiYwo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      role: sc-example
  template:
    metadata:
      name: sc-pod
      labels:
        role: sc-example
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sc-vol
              mountPath: /apps/secrets
              readOnly: true
      volumes:
        - name: sc-vol
          secret:
            secretName: secret
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc-sc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    role: sc-example
 





