apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydeploy
  labels:
    comp: app1
spec:
  replicas: 7
  selector:
    matchLabels:
      comp: app
  template:
    metadata:
      name: deploy-pod
      labels:
        comp: app
    spec:
      nodeSelector:
        comp: app
      containers:
        - name: deploy-tomcat
          image: leaddevops/kubeserve:v1
          ports:
            - containerPort: 80





